version: '3.9'

services:
  node:
    container_name: vue
    build: ./docker
    tty: true
    volumes:
      - "~/.ssh:/root/.ssh"
      - ".:/root/app"
    working_dir: "/root/app"
    restart: always